runners:
  vars:
    github_token: "GITHUB_ARC_TOKEN"

bot:
  vars:
    users_table_id: "GSHEET_CONFIG_TABLE_ID"
    telegram_token: "TELEGRAM_BOT_TOKEN"
    github_token: "GITHUB_TOKEN"
    google_sa_credentials: |
      {
        "type": "service_account",
        "project_id": "itmogus",
        "private_key_id": "123456789",
        "private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n",
        "client_email": "itmogus@itmogus.iam.gserviceaccount.com",
        "client_id": "123456789",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token"
      }
